workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    integrations:
      app_store_connect: "Codemagic API key"

    environment:
      vars:
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
        APP_IDENTIFIER: com.Workapp.SweetHome

      ios_signing:
        distribution_type: app_store
        bundle_identifier: $APP_IDENTIFIER

      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          sudo gem install xcodeproj -v '>=1.8' || true
          if [ -f "Podfile" ]; then
            pod install --repo-update
          fi

      - name: Setup code signing
        script: |
          xcode-project use-profiles --project "SweetTown.xcodeproj" --scheme "SweetTown"

      - name: Build IPA
        script: |
          if [ -f "SweetTown.xcworkspace" ]; then
            xcode-project build-ipa \
              --workspace "SweetTown.xcworkspace" \
              --scheme "SweetTown" \
              --config "Release"
          else
            xcode-project build-ipa \
              --project "SweetTown.xcodeproj" \
              --scheme "SweetTown" \
              --config "Release"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - /tmp/xcodebuild_archive/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # submit_to_app_store: true
