workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Workapp.SweetHome
        # Codemagic автоматически управляет сертификатами и профилями
      vars:
        TEAM_ID: 7LSL6C96XJ
      xcode: latest
      

    integrations:
      app_store_connect: "Codemagic API key"  # имя интеграции из Codemagic UI

    scripts:
      - name: Fetch and install signing files
        script: |
          app-store-connect fetch-signing-files "com.Workapp.SweetHome" --type IOS_APP_STORE --create
          keychain add-certificates
          cd SweetHome
          xcode-project use-profiles --team-id $TEAM_ID

      - name: Build iOS app (Release, App Store)
        script: |
          cd SweetHome
          xcode-project build-ipa \
            --project "SweetTown.xcodeproj" \
            --scheme "SweetTown" \
            --config "Release" \
            --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - /tmp/xcodebuild_archive/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # Закомментируйте submit_to_app_store пока не готовы к релизу
        # submit_to_app_store: true
