workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Workapp.SweetHome
      xcode: latest
      
    integrations:
      app_store_connect: "codemagic"  # Имя вашей интеграции из Codemagic UI

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          set -e
          cd SweetHome
          xcode-project use-profiles
      
      - name: Build and export iOS app
        script: |
          set -e
          cd SweetHome
          xcode-project build-ipa \
            --project "SweetTown.xcodeproj" \
            --scheme "SweetTown"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - /tmp/xcodebuild_archive/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
